title: r4nd site
email: y1s2s2f9@gmail.com
description: Nishitani-Lab Final Reprot
baseurl: "/r4nd"
url: "http://youssefomri.github.io" # the base hostname & protocol for your si
github_username:  youssefomri
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-org
permalink: /:categories/:short_year-:month-:day/:title
sass:
sass_dir: _sass
style: compressed
lsi: true

# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
